/**
 * guestService.js
 * Business logic for guest (tamu) registration.
 * Persists data to Supabase table: pst_guest
 *
 * Table columns:
 *   id_guest    – PK (generated by Supabase / serial)
 *   visit_date  – date
 *   guest_name  – text
 *   organization – text
 *   address     – text
 *   wa_number   – text
 *   guest_email – text
 *   pst_purpose – text  (jenis keperluan)
 *   purpose_desc – text (deskripsi keperluan)
 */

const GuestService = (() => {
  const TABLE = 'pst_guest';

  /**
   * Register a new guest — async, saves to Supabase.
   * @param {Object} data – form fields from registrationPage
   * @returns {Promise<{ success: boolean, id: string|null, message: string }>}
   */
  async function register(data) {
    // Client-side required-field guard (mirrors form validation)
    if (!data.nama || !data.instansi || !data.noWa || !data.jenisKeperluan || !data.deskripsi) {
      return { success: false, id: null, message: 'Data wajib belum lengkap.' };
    }

    // Map form fields → Supabase column names
    const payload = {
      visit_date:   data.tanggal    || new Date().toISOString().slice(0, 10),
      guest_name:   data.nama.trim(),
      organization: data.instansi.trim(),
      address:      (data.alamat   || '').trim(),
      wa_number:    data.noWa.trim(),
      guest_email:  (data.email    || '').trim(),
      pst_purpose:  data.jenisKeperluan.trim(),
      purpose_desc: data.deskripsi.trim(),
    };

    const { data: row, error } = await SupabaseService.insert(TABLE, payload);

    if (error) {
      console.error('[GuestService] insert error:', error);
      return { success: false, id: null, message: `Gagal menyimpan data: ${error}` };
    }

    return {
      success: true,
      id:      row?.id_guest ?? '–',
      message: 'Registrasi berhasil.',
    };
  }

  /**
   * Fetch all guests from Supabase (for admin use).
   * @returns {Promise<{ data: Array, error: string|null }>}
   */
  async function getAll() {
    return SupabaseService.select(TABLE);
  }

  return { register, getAll };
})();
