/**
 * guestService.js
 * Business logic for guest (tamu) registration.
 * Persists data to Supabase table: pst_guest,
 * then triggers QueueService to create a queue entry in pst_queue.
 *
 * Table columns (pst_guest):
 *   id_guest     – PK (serial, generated by Supabase)
 *   visit_date   – date
 *   guest_name   – text
 *   organization – text
 *   address      – text
 *   wa_number    – text
 *   guest_email  – text
 *   pst_purpose  – text  (jenis keperluan)
 *   purpose_desc – text  (deskripsi keperluan)
 */

const GuestService = (() => {
  const TABLE = 'pst_guest';
  const PURPOSE_MAP = {
    'Tugas sekolah/tugas kuliah': 1,
    'Pemerintahan': 2,
    'Komersial': 3,
    'Penelitian': 4,
    'Lainnya': 5
  };
  /**
   * Register a new guest and immediately create a queue entry.
   * @param {Object} data – form fields from registrationPage
   * @returns {Promise<{
   *   success:     boolean,
   *   guestId:     string|null,
   *   queueNumber: string|null,
   *   createdAt:   string|null,
   *   message:     string
   * }>}
   */
  async function register(data) {
    // Client-side required-field guard
    if (!data.nama || !data.instansi || !data.noWa || !data.jenisKeperluan || !data.deskripsi) {
      return { success: false, guestId: null, queueNumber: null, createdAt: null,
               message: 'Data wajib belum lengkap.' };
    }

    // ── Step 1: Insert guest row ───────────────────────────
    const payload = {
      visit_date:   data.tanggal    || new Date().toISOString().slice(0, 10),
      guest_name:   data.nama.trim(),
      organization: data.instansi.trim(),
      address:      (data.alamat   || '').trim(),
      wa_number:    data.noWa.trim(),
      guest_email:  (data.email    || '').trim(),
      id_purpose: PURPOSE_MAP[data.jenisKeperluan],
      purpose_desc: data.deskripsi.trim(),
    };

    const { data: guestRow, error: guestErr } = await SupabaseService.insert(TABLE, payload);

    if (guestErr) {
      console.error('[GuestService] insert pst_guest error:', guestErr);
      return { success: false, guestId: null, queueNumber: null, createdAt: null,
               message: `Gagal menyimpan data tamu: ${guestErr}` };
    }

    const guestId = guestRow?.id_guest;

    // ── Step 2: Create queue entry ─────────────────────────
    const {
      success:     qSuccess,
      queueNumber,
      createdAt,
      error:       qErr,
    } = await QueueService.create(guestId);

    if (!qSuccess) {
      console.error('[GuestService] create queue error:', qErr);
      // Guest was saved — queue creation failed. Return partial success
      // so the UI can still show the guest was registered, with a warning.
      return {
        success:     false,
        guestId:     guestId ?? null,
        queueNumber: null,
        createdAt:   null,
        message:     `Data tamu tersimpan, namun gagal membuat nomor antrian: ${qErr}`,
      };
    }

    return {
      success:     true,
      guestId:     guestId   ?? null,
      queueNumber: queueNumber,
      createdAt:   createdAt,
      message:     'Registrasi berhasil.',
    };
  }

  /**
   * Fetch all guests from Supabase (for admin use).
   * @returns {Promise<{ data: Array, error: string|null }>}
   */
  async function getAll() {
    return SupabaseService.select(TABLE);
  }

  return { register, getAll };
})();
