/**
 * queueService.js
 * Business logic for queue management.
 * Writes to Supabase table: pst_queue
 *
 * Table columns:
 *   id_queue     – PK (serial, generated by Supabase)
 *   id_guest     – FK → pst_guest.id_guest
 *   queue_number – text, format "PST-01", resets every day
 *   queue_status – text, default "Menunggu" (set by DB default)
 *   created_at   – timestamptz (set by DB default / now())
 *   called_at    – timestamptz (nullable, updated later)
 *   finished_at  – timestamptz (nullable, updated later)
 */

const QueueService = (() => {
  const TABLE    = 'pst_queue';
  const BASE_URL = 'https://fufjaptmggulmzjrefvg.supabase.co/rest/v1';
  const APIKEY   = 'sb_publishable_KpToL4zDIleZviiLL6hnvA_RXs3la0l';

  /** Shared request headers */
  const _headers = () => ({
    'Content-Type':  'application/json',
    'apikey':        APIKEY,
    'Authorization': `Bearer ${APIKEY}`,
  });

  /** Local date as YYYY-MM-DD */
  function _localDate(offsetDays = 0) {
    const d = new Date();
    d.setDate(d.getDate() + offsetDays);
    const pad = (n) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  }

  /** Format sequence number → "PST-01", "PST-12", etc. */
  function _fmt(n) {
    return `PST-${String(n).padStart(2, '0')}`;
  }

  /**
   * Query today's queues and return the next queue_number.
   * Uses URLSearchParams with repeated keys to send both
   * gte and lt filters on created_at (PostgREST requires this).
   *
   * @returns {Promise<{ number: string|null, error: string|null }>}
   */
  async function _nextNumber() {
    const today    = _localDate(0);
    const tomorrow = _localDate(1);

    try {
      const params = new URLSearchParams();
      params.append('select',     'queue_number');
      params.append('created_at', `gte.${today}T00:00:00+00`);
      params.append('created_at', `lt.${tomorrow}T00:00:00+00`);
      params.append('order',      'queue_number.desc');
      params.append('limit',      '1');

      const res  = await fetch(`${BASE_URL}/${TABLE}?${params}`, {
        method: 'GET', headers: _headers(),
      });
      const json = await res.json();

      if (!res.ok) {
        return { number: null, error: json?.message || `HTTP ${res.status}` };
      }

      if (!Array.isArray(json) || json.length === 0) {
        // No queues yet today → start from 1
        return { number: _fmt(1), error: null };
      }

      // "PST-05" → 5 → next is 6
      const lastSeq = parseInt((json[0].queue_number || 'PST-00').replace('PST-', ''), 10) || 0;
      return { number: _fmt(lastSeq + 1), error: null };

    } catch (err) {
      return { number: null, error: err.message || 'Network error.' };
    }
  }

  /**
   * Create a new queue entry linked to a guest.
   * Called immediately after a successful guest INSERT.
   *
   * @param {string|number} idGuest  – id_guest returned by pst_guest insert
   * @returns {Promise<{
   *   success:     boolean,
   *   queueNumber: string|null,
   *   createdAt:   string|null,
   *   error:       string|null
   * }>}
   */
  async function create(idGuest) {
    // 1. Get the next queue number for today
    const { number, error: numErr } = await _nextNumber();
    if (numErr) {
      return { success: false, queueNumber: null, createdAt: null, error: numErr };
    }

    // 2. Insert queue row — queue_status & created_at use DB defaults
    const { data: row, error: insertErr } = await SupabaseService.insert(TABLE, {
      id_guest:     idGuest,
      queue_number: number,
    });

    if (insertErr) {
      console.error('[QueueService] insert error:', insertErr);
      return { success: false, queueNumber: null, createdAt: null, error: insertErr };
    }

    return {
      success:     true,
      queueNumber: row?.queue_number ?? number,
      createdAt:   row?.created_at   ?? null,
      error:       null,
    };
  }

  return { create };
})();
